// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: claims.sql

package db

import (
	"context"

	"github.com/sqlc-dev/pqtype"
)

const deleteCustomClaim = `-- name: DeleteCustomClaim :exec
DELETE FROM custom_claims
WHERE user_id = $1 AND claim_key = $2
`

type DeleteCustomClaimParams struct {
	UserID   int32  `json:"user_id"`
	ClaimKey string `json:"claim_key"`
}

func (q *Queries) DeleteCustomClaim(ctx context.Context, arg DeleteCustomClaimParams) error {
	_, err := q.exec(ctx, q.deleteCustomClaimStmt, deleteCustomClaim, arg.UserID, arg.ClaimKey)
	return err
}

const getUserCustomClaims = `-- name: GetUserCustomClaims :many
SELECT claim_key, claim_value
FROM custom_claims
WHERE user_id = $1
`

type GetUserCustomClaimsRow struct {
	ClaimKey   string                `json:"claim_key"`
	ClaimValue pqtype.NullRawMessage `json:"claim_value"`
}

func (q *Queries) GetUserCustomClaims(ctx context.Context, userID int32) ([]GetUserCustomClaimsRow, error) {
	rows, err := q.query(ctx, q.getUserCustomClaimsStmt, getUserCustomClaims, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCustomClaimsRow
	for rows.Next() {
		var i GetUserCustomClaimsRow
		if err := rows.Scan(&i.ClaimKey, &i.ClaimValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCustomClaim = `-- name: UpsertCustomClaim :exec

INSERT INTO custom_claims (user_id, claim_key, claim_value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, claim_key) DO UPDATE
SET claim_value = $3, updated_at = CURRENT_TIMESTAMP
`

type UpsertCustomClaimParams struct {
	UserID     int32                 `json:"user_id"`
	ClaimKey   string                `json:"claim_key"`
	ClaimValue pqtype.NullRawMessage `json:"claim_value"`
}

// sql/queries/claims.sql
func (q *Queries) UpsertCustomClaim(ctx context.Context, arg UpsertCustomClaimParams) error {
	_, err := q.exec(ctx, q.upsertCustomClaimStmt, upsertCustomClaim, arg.UserID, arg.ClaimKey, arg.ClaimValue)
	return err
}
