// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.assignUserRoleStmt, err = db.PrepareContext(ctx, assignUserRole); err != nil {
		return nil, fmt.Errorf("error preparing query AssignUserRole: %w", err)
	}
	if q.createSecurityLogStmt, err = db.PrepareContext(ctx, createSecurityLog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSecurityLog: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteCustomClaimStmt, err = db.PrepareContext(ctx, deleteCustomClaim); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCustomClaim: %w", err)
	}
	if q.getRoleByNameStmt, err = db.PrepareContext(ctx, getRoleByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetRoleByName: %w", err)
	}
	if q.getSessionStmt, err = db.PrepareContext(ctx, getSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetSession: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUserByAuth0IDStmt, err = db.PrepareContext(ctx, getUserByAuth0ID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByAuth0ID: %w", err)
	}
	if q.getUserCustomClaimsStmt, err = db.PrepareContext(ctx, getUserCustomClaims); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserCustomClaims: %w", err)
	}
	if q.getUserMFAStatusStmt, err = db.PrepareContext(ctx, getUserMFAStatus); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserMFAStatus: %w", err)
	}
	if q.getUserRolesStmt, err = db.PrepareContext(ctx, getUserRoles); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserRoles: %w", err)
	}
	if q.getUserSecurityLogsStmt, err = db.PrepareContext(ctx, getUserSecurityLogs); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserSecurityLogs: %w", err)
	}
	if q.getUsersWithRolesStmt, err = db.PrepareContext(ctx, getUsersWithRoles); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsersWithRoles: %w", err)
	}
	if q.listActiveSessionsStmt, err = db.PrepareContext(ctx, listActiveSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveSessions: %w", err)
	}
	if q.listRolesStmt, err = db.PrepareContext(ctx, listRoles); err != nil {
		return nil, fmt.Errorf("error preparing query ListRoles: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.removeAllUserRolesStmt, err = db.PrepareContext(ctx, removeAllUserRoles); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveAllUserRoles: %w", err)
	}
	if q.removeUserRoleStmt, err = db.PrepareContext(ctx, removeUserRole); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveUserRole: %w", err)
	}
	if q.revokeSessionStmt, err = db.PrepareContext(ctx, revokeSession); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeSession: %w", err)
	}
	if q.updateSessionLastActiveStmt, err = db.PrepareContext(ctx, updateSessionLastActive); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionLastActive: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.updateUserMFAStatusStmt, err = db.PrepareContext(ctx, updateUserMFAStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserMFAStatus: %w", err)
	}
	if q.updateUserProfileStmt, err = db.PrepareContext(ctx, updateUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserProfile: %w", err)
	}
	if q.upsertCustomClaimStmt, err = db.PrepareContext(ctx, upsertCustomClaim); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertCustomClaim: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.assignUserRoleStmt != nil {
		if cerr := q.assignUserRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing assignUserRoleStmt: %w", cerr)
		}
	}
	if q.createSecurityLogStmt != nil {
		if cerr := q.createSecurityLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSecurityLogStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteCustomClaimStmt != nil {
		if cerr := q.deleteCustomClaimStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCustomClaimStmt: %w", cerr)
		}
	}
	if q.getRoleByNameStmt != nil {
		if cerr := q.getRoleByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRoleByNameStmt: %w", cerr)
		}
	}
	if q.getSessionStmt != nil {
		if cerr := q.getSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUserByAuth0IDStmt != nil {
		if cerr := q.getUserByAuth0IDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByAuth0IDStmt: %w", cerr)
		}
	}
	if q.getUserCustomClaimsStmt != nil {
		if cerr := q.getUserCustomClaimsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserCustomClaimsStmt: %w", cerr)
		}
	}
	if q.getUserMFAStatusStmt != nil {
		if cerr := q.getUserMFAStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserMFAStatusStmt: %w", cerr)
		}
	}
	if q.getUserRolesStmt != nil {
		if cerr := q.getUserRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserRolesStmt: %w", cerr)
		}
	}
	if q.getUserSecurityLogsStmt != nil {
		if cerr := q.getUserSecurityLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserSecurityLogsStmt: %w", cerr)
		}
	}
	if q.getUsersWithRolesStmt != nil {
		if cerr := q.getUsersWithRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsersWithRolesStmt: %w", cerr)
		}
	}
	if q.listActiveSessionsStmt != nil {
		if cerr := q.listActiveSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveSessionsStmt: %w", cerr)
		}
	}
	if q.listRolesStmt != nil {
		if cerr := q.listRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRolesStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.removeAllUserRolesStmt != nil {
		if cerr := q.removeAllUserRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeAllUserRolesStmt: %w", cerr)
		}
	}
	if q.removeUserRoleStmt != nil {
		if cerr := q.removeUserRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeUserRoleStmt: %w", cerr)
		}
	}
	if q.revokeSessionStmt != nil {
		if cerr := q.revokeSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeSessionStmt: %w", cerr)
		}
	}
	if q.updateSessionLastActiveStmt != nil {
		if cerr := q.updateSessionLastActiveStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionLastActiveStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.updateUserMFAStatusStmt != nil {
		if cerr := q.updateUserMFAStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserMFAStatusStmt: %w", cerr)
		}
	}
	if q.updateUserProfileStmt != nil {
		if cerr := q.updateUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserProfileStmt: %w", cerr)
		}
	}
	if q.upsertCustomClaimStmt != nil {
		if cerr := q.upsertCustomClaimStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertCustomClaimStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                          DBTX
	tx                          *sql.Tx
	assignUserRoleStmt          *sql.Stmt
	createSecurityLogStmt       *sql.Stmt
	createSessionStmt           *sql.Stmt
	createUserStmt              *sql.Stmt
	deleteCustomClaimStmt       *sql.Stmt
	getRoleByNameStmt           *sql.Stmt
	getSessionStmt              *sql.Stmt
	getUserStmt                 *sql.Stmt
	getUserByAuth0IDStmt        *sql.Stmt
	getUserCustomClaimsStmt     *sql.Stmt
	getUserMFAStatusStmt        *sql.Stmt
	getUserRolesStmt            *sql.Stmt
	getUserSecurityLogsStmt     *sql.Stmt
	getUsersWithRolesStmt       *sql.Stmt
	listActiveSessionsStmt      *sql.Stmt
	listRolesStmt               *sql.Stmt
	listUsersStmt               *sql.Stmt
	removeAllUserRolesStmt      *sql.Stmt
	removeUserRoleStmt          *sql.Stmt
	revokeSessionStmt           *sql.Stmt
	updateSessionLastActiveStmt *sql.Stmt
	updateUserStmt              *sql.Stmt
	updateUserMFAStatusStmt     *sql.Stmt
	updateUserProfileStmt       *sql.Stmt
	upsertCustomClaimStmt       *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		tx:                          tx,
		assignUserRoleStmt:          q.assignUserRoleStmt,
		createSecurityLogStmt:       q.createSecurityLogStmt,
		createSessionStmt:           q.createSessionStmt,
		createUserStmt:              q.createUserStmt,
		deleteCustomClaimStmt:       q.deleteCustomClaimStmt,
		getRoleByNameStmt:           q.getRoleByNameStmt,
		getSessionStmt:              q.getSessionStmt,
		getUserStmt:                 q.getUserStmt,
		getUserByAuth0IDStmt:        q.getUserByAuth0IDStmt,
		getUserCustomClaimsStmt:     q.getUserCustomClaimsStmt,
		getUserMFAStatusStmt:        q.getUserMFAStatusStmt,
		getUserRolesStmt:            q.getUserRolesStmt,
		getUserSecurityLogsStmt:     q.getUserSecurityLogsStmt,
		getUsersWithRolesStmt:       q.getUsersWithRolesStmt,
		listActiveSessionsStmt:      q.listActiveSessionsStmt,
		listRolesStmt:               q.listRolesStmt,
		listUsersStmt:               q.listUsersStmt,
		removeAllUserRolesStmt:      q.removeAllUserRolesStmt,
		removeUserRoleStmt:          q.removeUserRoleStmt,
		revokeSessionStmt:           q.revokeSessionStmt,
		updateSessionLastActiveStmt: q.updateSessionLastActiveStmt,
		updateUserStmt:              q.updateUserStmt,
		updateUserMFAStatusStmt:     q.updateUserMFAStatusStmt,
		updateUserProfileStmt:       q.updateUserProfileStmt,
		upsertCustomClaimStmt:       q.upsertCustomClaimStmt,
	}
}
