// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CreateSecurityLog(ctx context.Context, arg CreateSecurityLogParams) (SecurityLog, error)
	// sql/queries/security.sql
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteCustomClaim(ctx context.Context, arg DeleteCustomClaimParams) error
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	GetUser(ctx context.Context, id int32) (User, error)
	// sql/queries/users.sql
	GetUserByAuth0ID(ctx context.Context, auth0ID string) (User, error)
	GetUserCustomClaims(ctx context.Context, userID int32) ([]GetUserCustomClaimsRow, error)
	GetUserMFAStatus(ctx context.Context, id int32) (GetUserMFAStatusRow, error)
	GetUserRoles(ctx context.Context, userID int32) ([]Role, error)
	GetUserSecurityLogs(ctx context.Context, arg GetUserSecurityLogsParams) ([]GetUserSecurityLogsRow, error)
	// sql/queries/roles.sql
	GetUsersWithRoles(ctx context.Context) ([]GetUsersWithRolesRow, error)
	ListActiveSessions(ctx context.Context, userID int32) ([]ListActiveSessionsRow, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	RemoveAllUserRoles(ctx context.Context, userID int32) error
	RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	UpdateSessionLastActive(ctx context.Context, arg UpdateSessionLastActiveParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserMFAStatus(ctx context.Context, arg UpdateUserMFAStatusParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
	// sql/queries/claims.sql
	UpsertCustomClaim(ctx context.Context, arg UpsertCustomClaimParams) error
}

var _ Querier = (*Queries)(nil)
