// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: security.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSecurityLog = `-- name: CreateSecurityLog :one
INSERT INTO security_logs (
    user_id,
    event_type,
    event_description,
    ip_address,
    user_agent
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, event_type, event_description, ip_address, user_agent, created_at
`

type CreateSecurityLogParams struct {
	UserID           int32          `json:"user_id"`
	EventType        string         `json:"event_type"`
	EventDescription string         `json:"event_description"`
	IpAddress        pqtype.Inet    `json:"ip_address"`
	UserAgent        sql.NullString `json:"user_agent"`
}

func (q *Queries) CreateSecurityLog(ctx context.Context, arg CreateSecurityLogParams) (SecurityLog, error) {
	row := q.queryRow(ctx, q.createSecurityLogStmt, createSecurityLog,
		arg.UserID,
		arg.EventType,
		arg.EventDescription,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i SecurityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.EventDescription,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (
    user_id,
    device,
    location,
    ip_address,
    user_agent
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, device, location, ip_address, user_agent, last_active, created_at, revoked_at
`

type CreateSessionParams struct {
	UserID    int32          `json:"user_id"`
	Device    string         `json:"device"`
	Location  sql.NullString `json:"location"`
	IpAddress pqtype.Inet    `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
}

// sql/queries/security.sql
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.UserID,
		arg.Device,
		arg.Location,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Device,
		&i.Location,
		&i.IpAddress,
		&i.UserAgent,
		&i.LastActive,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, device, location, ip_address, user_agent, last_active, created_at, revoked_at FROM sessions
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type GetSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int32     `json:"user_id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.getSessionStmt, getSession, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Device,
		&i.Location,
		&i.IpAddress,
		&i.UserAgent,
		&i.LastActive,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserMFAStatus = `-- name: GetUserMFAStatus :one
SELECT
    id,
    email,
    mfa_enabled,
    updated_at
FROM users
WHERE id = $1
`

type GetUserMFAStatusRow struct {
	ID         int32        `json:"id"`
	Email      string       `json:"email"`
	MfaEnabled sql.NullBool `json:"mfa_enabled"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

func (q *Queries) GetUserMFAStatus(ctx context.Context, id int32) (GetUserMFAStatusRow, error) {
	row := q.queryRow(ctx, q.getUserMFAStatusStmt, getUserMFAStatus, id)
	var i GetUserMFAStatusRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.MfaEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSecurityLogs = `-- name: GetUserSecurityLogs :many
SELECT
    sl.id, sl.user_id, sl.event_type, sl.event_description, sl.ip_address, sl.user_agent, sl.created_at,
    u.email as user_email
FROM security_logs sl
JOIN users u ON u.id = sl.user_id
WHERE sl.user_id = $1
ORDER BY sl.created_at DESC
LIMIT $2
`

type GetUserSecurityLogsParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type GetUserSecurityLogsRow struct {
	ID               int32          `json:"id"`
	UserID           int32          `json:"user_id"`
	EventType        string         `json:"event_type"`
	EventDescription string         `json:"event_description"`
	IpAddress        pqtype.Inet    `json:"ip_address"`
	UserAgent        sql.NullString `json:"user_agent"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UserEmail        string         `json:"user_email"`
}

func (q *Queries) GetUserSecurityLogs(ctx context.Context, arg GetUserSecurityLogsParams) ([]GetUserSecurityLogsRow, error) {
	rows, err := q.query(ctx, q.getUserSecurityLogsStmt, getUserSecurityLogs, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSecurityLogsRow
	for rows.Next() {
		var i GetUserSecurityLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.EventDescription,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT
    s.id, s.user_id, s.device, s.location, s.ip_address, s.user_agent, s.last_active, s.created_at, s.revoked_at,
    u.email as user_email
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.user_id = $1
AND s.revoked_at IS NULL
ORDER BY s.last_active DESC
`

type ListActiveSessionsRow struct {
	ID         uuid.UUID      `json:"id"`
	UserID     int32          `json:"user_id"`
	Device     string         `json:"device"`
	Location   sql.NullString `json:"location"`
	IpAddress  pqtype.Inet    `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	LastActive sql.NullTime   `json:"last_active"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	RevokedAt  sql.NullTime   `json:"revoked_at"`
	UserEmail  string         `json:"user_email"`
}

func (q *Queries) ListActiveSessions(ctx context.Context, userID int32) ([]ListActiveSessionsRow, error) {
	rows, err := q.query(ctx, q.listActiveSessionsStmt, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSessionsRow
	for rows.Next() {
		var i ListActiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Device,
			&i.Location,
			&i.IpAddress,
			&i.UserAgent,
			&i.LastActive,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int32     `json:"user_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.exec(ctx, q.revokeSessionStmt, revokeSession, arg.ID, arg.UserID)
	return err
}

const updateSessionLastActive = `-- name: UpdateSessionLastActive :exec
UPDATE sessions
SET last_active = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
AND revoked_at IS NULL
`

type UpdateSessionLastActiveParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int32     `json:"user_id"`
}

func (q *Queries) UpdateSessionLastActive(ctx context.Context, arg UpdateSessionLastActiveParams) error {
	_, err := q.exec(ctx, q.updateSessionLastActiveStmt, updateSessionLastActive, arg.ID, arg.UserID)
	return err
}

const updateUserMFAStatus = `-- name: UpdateUserMFAStatus :exec
UPDATE users
SET
    mfa_enabled = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserMFAStatusParams struct {
	ID         int32        `json:"id"`
	MfaEnabled sql.NullBool `json:"mfa_enabled"`
}

func (q *Queries) UpdateUserMFAStatus(ctx context.Context, arg UpdateUserMFAStatusParams) error {
	_, err := q.exec(ctx, q.updateUserMFAStatusStmt, updateUserMFAStatus, arg.ID, arg.MfaEnabled)
	return err
}
