// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, auth0_id, picture)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, auth0_id, picture, created_at, updated_at
`

type CreateUserParams struct {
	Name    string         `json:"name"`
	Email   string         `json:"email"`
	Auth0ID string         `json:"auth0_id"`
	Picture sql.NullString `json:"picture"`
}

type CreateUserRow struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Auth0ID   string         `json:"auth0_id"`
	Picture   sql.NullString `json:"picture"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Name,
		arg.Email,
		arg.Auth0ID,
		arg.Picture,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Auth0ID,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, auth0_id, name, email, picture, mfa_enabled, created_at, updated_at, passwordless_enabled FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0ID,
		&i.Name,
		&i.Email,
		&i.Picture,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordlessEnabled,
	)
	return i, err
}

const getUserByAuth0ID = `-- name: GetUserByAuth0ID :one

SELECT id, auth0_id, name, email, picture, mfa_enabled, created_at, updated_at, passwordless_enabled FROM users WHERE auth0_id = $1 LIMIT 1
`

// sql/queries/users.sql
func (q *Queries) GetUserByAuth0ID(ctx context.Context, auth0ID string) (User, error) {
	row := q.queryRow(ctx, q.getUserByAuth0IDStmt, getUserByAuth0ID, auth0ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0ID,
		&i.Name,
		&i.Email,
		&i.Picture,
		&i.MfaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordlessEnabled,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    name,
    email,
    auth0_id,
    picture,
    mfa_enabled,
    created_at,
    updated_at
FROM users
ORDER BY name
`

type ListUsersRow struct {
	ID         int32          `json:"id"`
	Name       string         `json:"name"`
	Email      string         `json:"email"`
	Auth0ID    string         `json:"auth0_id"`
	Picture    sql.NullString `json:"picture"`
	MfaEnabled sql.NullBool   `json:"mfa_enabled"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Auth0ID,
			&i.Picture,
			&i.MfaEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    name = $2,
    email = $3,
    picture = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserParams struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Email   string         `json:"email"`
	Picture sql.NullString `json:"picture"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.exec(ctx, q.updateUserStmt, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Picture,
	)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    name = $2,
    picture = COALESCE($3, picture),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, email, auth0_id, picture, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Picture sql.NullString `json:"picture"`
}

type UpdateUserProfileRow struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Auth0ID   string         `json:"auth0_id"`
	Picture   sql.NullString `json:"picture"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.queryRow(ctx, q.updateUserProfileStmt, updateUserProfile, arg.ID, arg.Name, arg.Picture)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Auth0ID,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
